'use strict';

const HIGH_RISK_DB_THRESHOLD = 85;
const DEFAULT_NOISE_LIMIT = 50;
const MAX_NOISE_LIMIT = 200;
const DEFAULT_EVAL_LIMIT = 20;
const MAX_EVAL_LIMIT = 100;
const DEFAULT_VOLUME_LEVEL = 40;

const DB_LOW_THRESHOLD = 55;
const DB_MODERATE_THRESHOLD = 75;
const DB_HIGH_THRESHOLD = 95;
const DB_EXPOSURE_THRESHOLD = 70;

module.exports = {
  HIGH_RISK_DB_THRESHOLD,
  DEFAULT_NOISE_LIMIT,
  MAX_NOISE_LIMIT,
  DEFAULT_EVAL_LIMIT,
  MAX_EVAL_LIMIT,
  DEFAULT_VOLUME_LEVEL,
  DB_LOW_THRESHOLD,
  DB_MODERATE_THRESHOLD,
  DB_HIGH_THRESHOLD,
  DB_EXPOSURE_THRESHOLD,
};
