"""Named constants for risk thresholds and feature defaults."""

RISK_LOW_THRESHOLD = 25
RISK_MODERATE_THRESHOLD = 50
RISK_HIGH_THRESHOLD = 75

DEFAULT_AGE = 30.0
DEFAULT_VOLUME_LEVEL = 40.0
DEFAULT_AVG_SCORE = 5.0

SCORE_MIN = 0.0
SCORE_MAX = 100.0

NOISE_EXPOSURE_FACTOR_THRESHOLD = 1.5
HEADPHONE_HOURS_FACTOR_THRESHOLD = 4.0
VOLUME_LEVEL_FACTOR_THRESHOLD = 70.0
TEST_SCORE_FACTOR_THRESHOLD = 6.0
TOP_FACTORS_LIMIT = 4

CONFIDENCE_MAX = 0.95
CONFIDENCE_BASE = 0.55
CONFIDENCE_R2_WEIGHT = 0.4

YEARS_LOW_MIN = 20
YEARS_LOW_RANGE = 11
YEARS_MODERATE_MIN = 7
YEARS_MODERATE_RANGE = 9
YEARS_HIGH_MIN = 3
YEARS_HIGH_RANGE = 5
YEARS_VERY_HIGH_MIN = 1
YEARS_VERY_HIGH_RANGE = 3
